output_directory : /scratch/vmaurer/fold_temp
input_file : "config/sample_sheet.csv"
alphafold_data_directory : "/scratch/AlphaFold_DBs/2.3.0"

predictions_per_model : 1
number_of_recycles : 3

feature_creation_threads : 8
alphafold_inference : >
  gres=gpu:1 partition=gpu-el8
  qos=high constraint=gpu=A40|gpu=A100