input_files :
  - config/sample_sheet.csv
  - config/sample_sheet.csv
protein_delimiter : "_"

output_directory : /scratch/vmaurer/fold_temp
alphafold_data_directory : /scratch/AlphaFold_DBs/2.3.2

report_cutoff : 5.0
only_generate_features: False


create_feature_arguments:
  --save_msa_files: False
  --use_precomputed_msas: True
  --max_template_date: 2050-01-01
  --skip_existing: False

structure_inference_arguments:
  --num_predictions_per_model : 5
  --num_cycle: 24


feature_create_ram_bytes : 64000
structure_inference_ram_bytes: 32000

alphafold_inference_threads : 8
alphafold_inference : >
  gres=gpu:1 partition=gpu-el8
  qos=high constraint=gpu=3090

card_order : [gpu=3090, gpu=A40, gpu=H100, gpu=A100]
